python cross_decoding.py --model_string vgg11_imagenet --cross_type image_type
python cross_decoding.py --model_string vgg13_imagenet --cross_type image_type
python cross_decoding.py --model_string vgg16_imagenet --cross_type image_type
python cross_decoding.py --model_string vgg19_imagenet --cross_type image_type
python cross_decoding.py --model_string vgg11_bn_imagenet --cross_type image_type
python cross_decoding.py --model_string vgg13_bn_imagenet --cross_type image_type
python cross_decoding.py --model_string vgg16_bn_imagenet --cross_type image_type
python cross_decoding.py --model_string vgg19_bn_imagenet --cross_type image_type
python cross_decoding.py --model_string resnet18_imagenet --cross_type image_type
python cross_decoding.py --model_string resnet34_imagenet --cross_type image_type
python cross_decoding.py --model_string resnet50_imagenet --cross_type image_type
python cross_decoding.py --model_string resnet101_imagenet --cross_type image_type
python cross_decoding.py --model_string resnet152_imagenet --cross_type image_type
python cross_decoding.py --model_string squeezenet1_0_imagenet --cross_type image_type
python cross_decoding.py --model_string squeezenet1_1_imagenet --cross_type image_type
python cross_decoding.py --model_string densenet121_imagenet --cross_type image_type
python cross_decoding.py --model_string densenet161_imagenet --cross_type image_type
python cross_decoding.py --model_string densenet169_imagenet --cross_type image_type
python cross_decoding.py --model_string densenet201_imagenet --cross_type image_type
python cross_decoding.py --model_string googlenet_imagenet --cross_type image_type
python cross_decoding.py --model_string shufflenet_v2_x0_5_imagenet --cross_type image_type
python cross_decoding.py --model_string shufflenet_v2_x1_0_imagenet --cross_type image_type
python cross_decoding.py --model_string mobilenet_v2_imagenet --cross_type image_type
python cross_decoding.py --model_string resnext50_32x4d_imagenet --cross_type image_type
python cross_decoding.py --model_string resnext101_32x8d_imagenet --cross_type image_type
python cross_decoding.py --model_string wide_resnet50_2_imagenet --cross_type image_type
python cross_decoding.py --model_string wide_resnet101_2_imagenet --cross_type image_type
python cross_decoding.py --model_string mnasnet0_5_imagenet --cross_type image_type
python cross_decoding.py --model_string mnasnet1_0_imagenet --cross_type image_type
python cross_decoding.py --model_string cait_s24_224_imagenet --cross_type image_type
python cross_decoding.py --model_string convit_base_imagenet --cross_type image_type
python cross_decoding.py --model_string deit_base_patch16_224_imagenet --cross_type image_type
python cross_decoding.py --model_string deit_tiny_patch16_224_imagenet --cross_type image_type
python cross_decoding.py --model_string cspdarknet53_imagenet --cross_type image_type
python cross_decoding.py --model_string dla34_imagenet --cross_type image_type
python cross_decoding.py --model_string eca_nfnet_l0_imagenet --cross_type image_type
python cross_decoding.py --model_string eca_nfnet_l1_imagenet --cross_type image_type
python cross_decoding.py --model_string efficientnetv2_rw_s_imagenet --cross_type image_type
python cross_decoding.py --model_string gernet_s_imagenet --cross_type image_type
python cross_decoding.py --model_string ghostnet_100_imagenet --cross_type image_type
python cross_decoding.py --model_string hardcorenas_a_imagenet --cross_type image_type
python cross_decoding.py --model_string hardcorenas_f_imagenet --cross_type image_type
python cross_decoding.py --model_string levit_128_imagenet --cross_type image_type
python cross_decoding.py --model_string inception_resnet_v2_imagenet --cross_type image_type
python cross_decoding.py --model_string inception_v3_imagenet --cross_type image_type
python cross_decoding.py --model_string inception_v4_imagenet --cross_type image_type
python cross_decoding.py --model_string mixer_b16_224_imagenet --cross_type image_type
python cross_decoding.py --model_string mixer_l16_224_imagenet --cross_type image_type
python cross_decoding.py --model_string mobilenetv3_rw_imagenet --cross_type image_type
python cross_decoding.py --model_string nasnetalarge_imagenet --cross_type image_type
python cross_decoding.py --model_string nf_resnet50_imagenet --cross_type image_type
python cross_decoding.py --model_string pit_b_224_imagenet --cross_type image_type
python cross_decoding.py --model_string pit_ti_224_imagenet --cross_type image_type
python cross_decoding.py --model_string regnetx_064_imagenet --cross_type image_type
python cross_decoding.py --model_string regnety_064_imagenet --cross_type image_type
python cross_decoding.py --model_string seresnext50_32x4d_imagenet --cross_type image_type
python cross_decoding.py --model_string skresnext50_32x4d_imagenet --cross_type image_type
python cross_decoding.py --model_string spnasnet_100_imagenet --cross_type image_type
python cross_decoding.py --model_string swin_base_patch4_window7_224_imagenet --cross_type image_type
python cross_decoding.py --model_string swin_tiny_patch4_window7_224_imagenet --cross_type image_type
python cross_decoding.py --model_string tnt_s_patch16_224_imagenet --cross_type image_type
python cross_decoding.py --model_string twins_pcpvt_base_imagenet --cross_type image_type
python cross_decoding.py --model_string twins_svt_base_imagenet --cross_type image_type
python cross_decoding.py --model_string visformer_small_imagenet --cross_type image_type
python cross_decoding.py --model_string vit_tiny_patch16_224_imagenet --cross_type image_type
python cross_decoding.py --model_string vit_base_patch16_224_imagenet --cross_type image_type
python cross_decoding.py --model_string vit_base_patch32_224_imagenet --cross_type image_type
python cross_decoding.py --model_string xception_imagenet --cross_type image_type
python cross_decoding.py --model_string dino_vits16_selfsupervised --cross_type image_type
python cross_decoding.py --model_string dino_vits8_selfsupervised --cross_type image_type
python cross_decoding.py --model_string dino_vitb16_selfsupervised --cross_type image_type
python cross_decoding.py --model_string dino_vitb8_selfsupervised --cross_type image_type
python cross_decoding.py --model_string dino_xcit_small_12_p16_selfsupervised --cross_type image_type
python cross_decoding.py --model_string dino_resnet50_selfsupervised --cross_type image_type
python cross_decoding.py --model_string ViT-B/32_clip --cross_type image_type
python cross_decoding.py --model_string ViT-B/16_clip --cross_type image_type
python cross_decoding.py --model_string ResNet50-JigSaw-P100_selfsupervised --cross_type image_type
python cross_decoding.py --model_string ResNet50-JigSaw-Goyal19_selfsupervised --cross_type image_type
python cross_decoding.py --model_string ResNet50-RotNet_selfsupervised --cross_type image_type
python cross_decoding.py --model_string ResNet50-ClusterFit-16K-RotNet_selfsupervised --cross_type image_type
python cross_decoding.py --model_string ResNet50-NPID-4KNegative_selfsupervised --cross_type image_type
python cross_decoding.py --model_string ResNet50-PIRL_selfsupervised --cross_type image_type
python cross_decoding.py --model_string ResNet50-SimCLR_selfsupervised --cross_type image_type
python cross_decoding.py --model_string ResNet50-DeepClusterV2-2x224_selfsupervised --cross_type image_type
python cross_decoding.py --model_string ResNet50-DeepClusterV2-2x224+6x96_selfsupervised --cross_type image_type
python cross_decoding.py --model_string ResNet50-SwAV-BS4096-2x224_selfsupervised --cross_type image_type
python cross_decoding.py --model_string ResNet50-SwAV-BS4096-2x224+6x96_selfsupervised --cross_type image_type
python cross_decoding.py --model_string ResNet50-MoCoV2-BS256_selfsupervised --cross_type image_type
python cross_decoding.py --model_string ResNet50-BarlowTwins-BS2048_selfsupervised --cross_type image_type
python cross_decoding.py --model_string vgg11_imagenet --cross_type affect
python cross_decoding.py --model_string vgg13_imagenet --cross_type affect
python cross_decoding.py --model_string vgg16_imagenet --cross_type affect
python cross_decoding.py --model_string vgg19_imagenet --cross_type affect
python cross_decoding.py --model_string vgg11_bn_imagenet --cross_type affect
python cross_decoding.py --model_string vgg13_bn_imagenet --cross_type affect
python cross_decoding.py --model_string vgg16_bn_imagenet --cross_type affect
python cross_decoding.py --model_string vgg19_bn_imagenet --cross_type affect
python cross_decoding.py --model_string resnet18_imagenet --cross_type affect
python cross_decoding.py --model_string resnet34_imagenet --cross_type affect
python cross_decoding.py --model_string resnet50_imagenet --cross_type affect
python cross_decoding.py --model_string resnet101_imagenet --cross_type affect
python cross_decoding.py --model_string resnet152_imagenet --cross_type affect
python cross_decoding.py --model_string squeezenet1_0_imagenet --cross_type affect
python cross_decoding.py --model_string squeezenet1_1_imagenet --cross_type affect
python cross_decoding.py --model_string densenet121_imagenet --cross_type affect
python cross_decoding.py --model_string densenet161_imagenet --cross_type affect
python cross_decoding.py --model_string densenet169_imagenet --cross_type affect
python cross_decoding.py --model_string densenet201_imagenet --cross_type affect
python cross_decoding.py --model_string googlenet_imagenet --cross_type affect
python cross_decoding.py --model_string shufflenet_v2_x0_5_imagenet --cross_type affect
python cross_decoding.py --model_string shufflenet_v2_x1_0_imagenet --cross_type affect
python cross_decoding.py --model_string mobilenet_v2_imagenet --cross_type affect
python cross_decoding.py --model_string resnext50_32x4d_imagenet --cross_type affect
python cross_decoding.py --model_string resnext101_32x8d_imagenet --cross_type affect
python cross_decoding.py --model_string wide_resnet50_2_imagenet --cross_type affect
python cross_decoding.py --model_string wide_resnet101_2_imagenet --cross_type affect
python cross_decoding.py --model_string mnasnet0_5_imagenet --cross_type affect
python cross_decoding.py --model_string mnasnet1_0_imagenet --cross_type affect
python cross_decoding.py --model_string cait_s24_224_imagenet --cross_type affect
python cross_decoding.py --model_string convit_base_imagenet --cross_type affect
python cross_decoding.py --model_string deit_base_patch16_224_imagenet --cross_type affect
python cross_decoding.py --model_string deit_tiny_patch16_224_imagenet --cross_type affect
python cross_decoding.py --model_string cspdarknet53_imagenet --cross_type affect
python cross_decoding.py --model_string dla34_imagenet --cross_type affect
python cross_decoding.py --model_string eca_nfnet_l0_imagenet --cross_type affect
python cross_decoding.py --model_string eca_nfnet_l1_imagenet --cross_type affect
python cross_decoding.py --model_string efficientnetv2_rw_s_imagenet --cross_type affect
python cross_decoding.py --model_string gernet_s_imagenet --cross_type affect
python cross_decoding.py --model_string ghostnet_100_imagenet --cross_type affect
python cross_decoding.py --model_string hardcorenas_a_imagenet --cross_type affect
python cross_decoding.py --model_string hardcorenas_f_imagenet --cross_type affect
python cross_decoding.py --model_string levit_128_imagenet --cross_type affect
python cross_decoding.py --model_string inception_resnet_v2_imagenet --cross_type affect
python cross_decoding.py --model_string inception_v3_imagenet --cross_type affect
python cross_decoding.py --model_string inception_v4_imagenet --cross_type affect
python cross_decoding.py --model_string mixer_b16_224_imagenet --cross_type affect
python cross_decoding.py --model_string mixer_l16_224_imagenet --cross_type affect
python cross_decoding.py --model_string mobilenetv3_rw_imagenet --cross_type affect
python cross_decoding.py --model_string nasnetalarge_imagenet --cross_type affect
python cross_decoding.py --model_string nf_resnet50_imagenet --cross_type affect
python cross_decoding.py --model_string pit_b_224_imagenet --cross_type affect
python cross_decoding.py --model_string pit_ti_224_imagenet --cross_type affect
python cross_decoding.py --model_string regnetx_064_imagenet --cross_type affect
python cross_decoding.py --model_string regnety_064_imagenet --cross_type affect
python cross_decoding.py --model_string seresnext50_32x4d_imagenet --cross_type affect
python cross_decoding.py --model_string skresnext50_32x4d_imagenet --cross_type affect
python cross_decoding.py --model_string spnasnet_100_imagenet --cross_type affect
python cross_decoding.py --model_string swin_base_patch4_window7_224_imagenet --cross_type affect
python cross_decoding.py --model_string swin_tiny_patch4_window7_224_imagenet --cross_type affect
python cross_decoding.py --model_string tnt_s_patch16_224_imagenet --cross_type affect
python cross_decoding.py --model_string twins_pcpvt_base_imagenet --cross_type affect
python cross_decoding.py --model_string twins_svt_base_imagenet --cross_type affect
python cross_decoding.py --model_string visformer_small_imagenet --cross_type affect
python cross_decoding.py --model_string vit_tiny_patch16_224_imagenet --cross_type affect
python cross_decoding.py --model_string vit_base_patch16_224_imagenet --cross_type affect
python cross_decoding.py --model_string vit_base_patch32_224_imagenet --cross_type affect
python cross_decoding.py --model_string xception_imagenet --cross_type affect
python cross_decoding.py --model_string dino_vits16_selfsupervised --cross_type affect
python cross_decoding.py --model_string dino_vits8_selfsupervised --cross_type affect
python cross_decoding.py --model_string dino_vitb16_selfsupervised --cross_type affect
python cross_decoding.py --model_string dino_vitb8_selfsupervised --cross_type affect
python cross_decoding.py --model_string dino_xcit_small_12_p16_selfsupervised --cross_type affect
python cross_decoding.py --model_string dino_resnet50_selfsupervised --cross_type affect
python cross_decoding.py --model_string ViT-B/32_clip --cross_type affect
python cross_decoding.py --model_string ViT-B/16_clip --cross_type affect
python cross_decoding.py --model_string ResNet50-JigSaw-P100_selfsupervised --cross_type affect
python cross_decoding.py --model_string ResNet50-JigSaw-Goyal19_selfsupervised --cross_type affect
python cross_decoding.py --model_string ResNet50-RotNet_selfsupervised --cross_type affect
python cross_decoding.py --model_string ResNet50-ClusterFit-16K-RotNet_selfsupervised --cross_type affect
python cross_decoding.py --model_string ResNet50-NPID-4KNegative_selfsupervised --cross_type affect
python cross_decoding.py --model_string ResNet50-PIRL_selfsupervised --cross_type affect
python cross_decoding.py --model_string ResNet50-SimCLR_selfsupervised --cross_type affect
python cross_decoding.py --model_string ResNet50-DeepClusterV2-2x224_selfsupervised --cross_type affect
python cross_decoding.py --model_string ResNet50-DeepClusterV2-2x224+6x96_selfsupervised --cross_type affect
python cross_decoding.py --model_string ResNet50-SwAV-BS4096-2x224_selfsupervised --cross_type affect
python cross_decoding.py --model_string ResNet50-SwAV-BS4096-2x224+6x96_selfsupervised --cross_type affect
python cross_decoding.py --model_string ResNet50-MoCoV2-BS256_selfsupervised --cross_type affect
python cross_decoding.py --model_string ResNet50-BarlowTwins-BS2048_selfsupervised --cross_type affect